name: One Way Coffee
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02688172
title: PLUS ONE COFFEE CO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdc9c0'
    - '#68543a'
    - '#efd400'
    - '#afa497'
    - '#fefefe'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
