layout_spectrum: 1
typography_spectrum: 0.02688172
color:
  saturation: 0.8438364
  lightness: 0.1987822
  brandStrength: 0.9121864
  brandColors:
    - '#E8E8E8'
    - '#919191'
    - '#656565'
    - '#000000'
    - '#E36E76'
  rhythmicContrast: 0.5003123
name: One Way Coffee
